import { authenticated } from "../../middlewares/authenticated";
import { authorizeRoles } from "../../middlewares/authorized";
import { catchAsync } from "../../utils/catchAsync";
import AuthRoute from "./auth";
import rolesRouter from "./roles";
import  pickupPointRouter from "./pickuppoint";
import adminRouter from "./admin";
import busRouter from "./bus";
import RoutRouter from "./Rout";
import profileRouter from "./profile";
import diverRouter from "./driver";
import departmentRouter from "./department";
import parentRouter from "./parent";
import codriverRouter from "./codriver"
import studentRouter from "./student";
import subscribtionRouter from "./subscribtion";
import rideRouter from "./ride";
import paymentRouter from "./payment";
import { Router } from "express";
const route = Router();
route.use("/auth",catchAsync(AuthRoute));
route.use(authenticated, authorizeRoles("admin","organizer"));
route.use("/roles",catchAsync(rolesRouter));
route.use("/departments",catchAsync(departmentRouter));
route.use("/pickuppoints",catchAsync(pickupPointRouter));
route.use("/admins",catchAsync(adminRouter));
route.use("/codrivers",catchAsync(codriverRouter));
route.use("/drivers",catchAsync(diverRouter));
route.use("/rides",catchAsync(rideRouter));
route.use("/subscribtions",catchAsync(subscribtionRouter));
route.use("/buses",catchAsync(busRouter));
route.use("/students",catchAsync(studentRouter));
route.use("/parents",catchAsync(parentRouter));
route.use("/routes",catchAsync(RoutRouter));
route.use("/profile",catchAsync(profileRouter));
route.use("/payments",catchAsync(paymentRouter));
export default route;
