import { authenticated } from "../../middlewares/authenticated";
import { authorizeRoles } from "../../middlewares/authorized";
import { catchAsync } from "../../utils/catchAsync";
import AuthRoute from "./auth";
import rolesRouter from "./roles";
import  pickupPointRouter from "./pickuppoint";
import adminRouter from "./admin";
import busRouter from "./bus";
import RoutRouter from "./Rout";
import profileRouter from "./profile";
import diverRouter from "./driver";
import departmentRouter from "./department";
import codriverRouter from "./codriver"
import { Router } from "express";
const route = Router();
route.use("/auth",catchAsync(AuthRoute));
route.use(authenticated, authorizeRoles("admin","organizer"));
route.use("/roles",catchAsync(rolesRouter));
route.use("/departments",catchAsync(departmentRouter));
route.use("/pickuppoints",catchAsync(pickupPointRouter));
route.use("/admins",catchAsync(adminRouter));
route.use("/codrivers",catchAsync(codriverRouter));
route.use("/drivers",catchAsync(diverRouter));
route.use("/buses",catchAsync(busRouter));
route.use("/routes",catchAsync(RoutRouter));
route.use("/profile",catchAsync(profileRouter));
export default route;
