import { Router } from "express";
import {authorizeRoles} from "../../middlewares/authorized"
import { authenticated } from "../../middlewares/authenticated";
import authRouter from "./auth";
import profileRouter from "./profile";
import childRouter from "./parent/student";
import rideRouter from "./parent/rides";
import parentPaymentRouter from "./parent/parentPayment";
import rideRouterDriver from "./driver/rides";
import parentPlanRouter from "./parent/parentPlans";
import walletRechargeRequestRouter from "./parent/walletRechargeRequest";
import parentSubscriptionRouter from "./parent/parentSubscription";
import paymentMethodRouter from "./parent/parentPaymentMethods";
import organizationServicesRouter from "./parent/OrganizationServices";
import notesRouter from "./parent/notes";
const router = Router();

router.use("/auth", authRouter);
router.use(authenticated);
router.use("/profile", profileRouter);
router.use("/children", childRouter);
router.use("/rides", rideRouter);
router.use("/parentpayments", parentPaymentRouter);
router.use("/driver/rides", rideRouterDriver);
router.use("/parentplans", parentPlanRouter);
router.use("/parentsubscriptions", parentSubscriptionRouter);
router.use("/paymentmethods", paymentMethodRouter);
router.use("/walletrequests", walletRechargeRequestRouter);
router.use("/organizationservices", organizationServicesRouter);
router.use("/notes", notesRouter);
export default router;